### PR TITLE
chore: add blog post verdaccio with verdaccio-ldap and docker

### PR DESCRIPTION
**Pull request by kopax**

### CODE REVIEW

**Comment by kopax** [comment]
> unfortunately docusaurus does not support `[x]` or `:whale` format, could you update it ? 

Not sure what format are you talking about, this is enriched markdown used by GitHub, do you mean I should remove all emoticon `:whale:`, `:tada:` ,`:ballon:` (all emoticon starting and ending with `:`)?

I understand for `[x]`, but that can be displayed as text I guess. Maybe I can format a little more

> I think unicode emojis are completely valid.

Can you give me an example of synthax?

Even better, can you tell me how to start the website locally?

I have followed:

> # Running the website locally
> You should run all these tasks from the inner `/website` folder.
> 
> The commands you need to use for serving the site locally:
> - `yarn install` - installs all dependencies.
> - `yarn start` - runs a local server that launches the Verdaccio documentation site on http://localhost:3000/


And I had:

```
yarn install
yarn install v1.19.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.06s.
dka@dev-11:[~/workspace/github.com/kopax/website (master)]: yarn start
yarn run v1.19.0
error Couldn't find a package.json file in "/home/dka/workspace/github.com/kopax/website"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by juanpicado** [comment]
you need to go one more level `cd website/website` -> `yarn start`

**Comment by kopax** [comment]
```
dka@dev-11:[~/workspace/github.com/kopax/website/website (master)]: yarn
yarn install v1.19.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.verdaccio.org/express/-/express-4.18.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/dka/workspace/github.com/kopax/website/website/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by kopax** [comment]
It's all good now.

**Pull request merged**
