### PR TITLE
Fix version links

### PR DESCRIPTION
**Pull request by VentyCZ**
Fixes https://github.com/verdaccio/website/issues/178

### CODE REVIEW

**Comment by juanpicado** [comment]
@sergiohgz @VentyCZ unfortunately this PR breaks the master, we need to undo this changes and try to find a different solution

```
rm 'zh-CN/versions.html'
rm 'zh-CN/versions/index.html'
Error: Copying build assets failed with error 'Error: ENOENT: no such file or directory, stat 'build/website''
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

**Comment by VentyCZ** [comment]
@juanpicado Yeah, I saw that. Will try to fix it other way, probably use the repoUrl directly from the config - did not see that before.

**Comment by sergiohgz** [comment]
@juanpicado you are right, we have to make better CI in this repo. @VentyCZ let me a moment to revert master branch :wink:

**Comment by VentyCZ** [comment]
@sergiohgz @juanpicado Ok, created another PR for this: https://github.com/verdaccio/website/pull/182

**Pull request merged**
