### PR TITLE
Chore: updated chown command in docker.md

### PR DESCRIPTION
**Pull request by ShawnToubeau**
Fix for the following issue: https://github.com/verdaccio/website/issues/132

### CODE REVIEW

**Comment by juanpicado** [comment]
:) read the alert 🚨 part https://github.com/verdaccio/website/blob/master/CONTRIBUTING.md

**Comment by ShawnToubeau** [comment]
My bad! I overlooked that part. I think it's correct now? Let me know if you need any other changes :)

**Comment by ShawnToubeau** [comment]
Oh wait. I just noticed it didn't completely revert some of the other files. I'll fix that asap to be correct.

**Comment by ShawnToubeau** [comment]
Closing to start over. Git skills are not good enough to know how to undo changes 😅

**Comment by juanpicado** [comment]
ok no problemo :-)

**Pull request closed without merging**
